[phases.setup]
nixPkgs = ["php82", "php82Packages.composer", "apache"]

[phases.install]
# Comando executado a partir da raiz do repositório
cmds = ["composer install --working-dir=test_sandox/test_sandox --no-dev --optimize-autoloader"]

[variables]
# Indica ao Railway onde está o ponto de entrada do seu site
NIXPACKS_PHP_ROOT_DIR = "test_sandox/test_sandox"